import {
  Buttons,
  Title,
  Content,
  SelectField,
  ImageField,
  SettingsGroup,
} from '../fields'

const Config = {
  label: 'Blocks',
  name: 'blocks',
  widget: 'list',
  types: [
    {
      label: 'Hero',
      name: 'hero',
      widget: 'object',
      summary: '{{fields.title}}',
      fields: [
        Title,
        Content,
        Buttons,
        ImageField(),
        SelectField('none', ['none', 'signature'], 'Decoration', 'decoration'),
        SelectField('default', ['default', 'aside']),
      ],
    },
    {
      label: 'Title',
      name: 'title',
      widget: 'object',
      summary: '{{fields.title}}',
      fields: [
        Title,
        Content,
        Buttons,
        SelectField('default', ['default', 'quote', 'small']),
        SelectField(
          'centered',
          ['default', 'centered'],
          'Alignment',
          'alignment',
        ),
        SettingsGroup,
      ],
    },
    {
      label: 'Content',
      name: 'content',
      widget: 'object',
      fields: [Content, SettingsGroup],
    },
    {
      label: 'Content with Image',
      name: 'content_image',
      widget: 'object',
      summary: '{{fields.title}}',
      fields: [
        ImageField(),
        Title,
        Content,
        Buttons,
        SelectField('default', ['default', 'reversed']),
        SettingsGroup,
      ],
    },
    {
      label: 'Columns',
      name: 'columns',
      summary: '{{fields.title}}',
      widget: 'object',
      fields: [
        {
          label: 'Columns',
          name: 'columns',
          widget: 'list',
          summary: '{{fields.title}}',
          fields: [Title, Content, ImageField()],
        },
        SettingsGroup,
      ],
    },
    {
      label: 'Articles',
      name: 'articles',
      widget: 'object',
      summary: '{{fields.title}}',
      fields: [
        Title,
        Content,
        Buttons,
        {
          label: 'Relation',
          name: 'relation',
          widget: 'relation',
          collection: 'categories',
          search_fields: ['name'],
          display_fields: ['{{id}} - {{name}}'],
          value_field: 'id',
          required: false,
        },
        SelectField('default', ['default', 'promoted']),
        SelectField(
          'by_category',
          ['by_category', 'recent'],
          'Display',
          'display',
        ),
        SettingsGroup,
      ],
    },
    {
      label: 'Video',
      name: 'video',
      widget: 'object',
      fields: [
        Title,
        Content,
        ImageField(),
        {
          label: 'Videos',
          name: 'videos',
          widget: 'relation',
          collection: 'videos',
          search_fields: ['id'],
          display_fields: ['title'],
          value_field: 'id',
          multiple: true,
          required: false,
        },
      ],
      SettingsGroup,
    },
    {
      label: 'Media',
      name: 'media',
      widget: 'object',
      fields: [
        Title,
        Content,
        ImageField(),
        {
          label: 'Media',
          name: 'media',
          widget: 'relation',
          collection: 'media',
          search_fields: ['id'],
          display_fields: ['title'],
          value_field: 'id',
          multiple: true,
          required: false,
        },
      ],
    },
    {
      label: 'Form',
      name: 'form',
      widget: 'object',
      summary: '{{fields.form.title}}',
      fields: [
        {
          label: 'Form',
          name: 'form',
          widget: 'relation',
          collection: 'forms',
          search_fields: ['title'],
          display_fields: ['{{id}} - {{title}}'],
          value_field: 'id',
          required: false,
        },
      ],
    },
  ],
}

export default Config
